import type { Job, Task, Workflow } from "../contracts/durable";
import type { ApprovalStore } from "../runtime/approval-store";
import type { AuthorityStore } from "../runtime/authority-store";
import type { BudgetStore } from "../runtime/budget-store";
import type { CandidateIntegrationService } from "../runtime/candidate-integration-service";
import type { CouncilRecord, CouncilStore } from "../runtime/council-store";
import type { AuthenticatedCredential, CredentialStore } from "../runtime/credential-store";
import type { DirectedMailbox } from "../runtime/directed-mailbox";
import type { FleetProfileStore } from "../runtime/fleet-profile-store";
import type { GoalCoordinatorService } from "../runtime/goal-coordinator-service";
import type { GoalStore } from "../runtime/goal-store";
import type { OrchestrationStateStore } from "../runtime/orchestration-state";
import type { PersistentMessageQueue } from "../runtime/message-queue";
import type { ProjectStateOptions } from "../runtime/project-state";
import type { ProjectTrustStore } from "../runtime/project-trust-store";
import type { WorkflowStore } from "../runtime/workflow-store";
import type { JobStore } from "./job-store";
import type { RunEventStore } from "./run-event-store";
import type { TaskStore } from "./task-store";
import type { LeadBindingStore } from "../runtime/lead-binding";
import type { Receipt } from "../contracts/receipt";
import type { ExportedReceipt, ReceiptVerificationVerdict } from "../runtime/receipt-verify";

type GoalRecord = NonNullable<ReturnType<GoalStore["get"]>>;

export type DaemonRouteContext = {
  projectId: string;
  projectRoot: string;
  /** Read live: the capability can be activated after handlers are built. */
  experimentalSessionsEnabled: () => boolean;
  activateExperimentalSessions: (credential: AuthenticatedCredential) => unknown;
  stateOptions?: ProjectStateOptions;
  extensionInfo: () => {
    digest: string;
    adapters: readonly string[];
    providers: readonly string[];
    pricing: readonly string[];
  };
  leads: LeadBindingStore;
  useLead: (host: string, credential: AuthenticatedCredential) => unknown;
  releaseLead: (credential: AuthenticatedCredential) => unknown;
  provisionObserver: (credential: AuthenticatedCredential) => unknown;
  observerSnapshot: () => unknown;
  observerEvents: (params: { afterCursor?: number; limit: number }) => unknown;
  trust: ProjectTrustStore;
  fleets: FleetProfileStore;
  fleetHealth: (profile: NonNullable<ReturnType<FleetProfileStore["get"]>>) => unknown;
  startGoal: (params: Record<string, unknown>, credential: AuthenticatedCredential) => unknown;
  goalCoordinator: GoalCoordinatorService;
  goals: GoalStore;
  directedMailbox: DirectedMailbox;
  requireGoal: (goalId: string) => GoalRecord;
  cancelGoalAs: (goalId: string, actor: string) => unknown;
  approvals: ApprovalStore;
  resolveApproval: (params: { approvalId: string; decision: "approved" | "rejected"; resolution: string }, credential: AuthenticatedCredential) => unknown;
  candidates: CandidateIntegrationService;
  credentials: CredentialStore;
  authority: AuthorityStore;
  budgets: BudgetStore;
  assertRequestedSessionOwnership: (params: Record<string, unknown>, credential: AuthenticatedCredential) => void;
  submitRun: (params: Record<string, unknown>, principal: string) => unknown;
  jobs: JobStore;
  requireJob: (jobId: string) => Job;
  requireJobFor: (jobId: string, credential: AuthenticatedCredential) => Job;
  cancelRun: (jobId: string) => unknown;
  waitRun: (jobId: string, timeoutMs?: number) => Promise<Job>;
  visibleJobs: (credential: AuthenticatedCredential, jobId?: string) => Job[];
  runEvents: RunEventStore;
  tasks: TaskStore;
  requireTask: (taskId: string) => Task;
  assertTaskVisible: (task: Task, credential: AuthenticatedCredential) => void;
  isTaskVisible: (task: Task, credential: AuthenticatedCredential) => boolean;
  messages: PersistentMessageQueue;
  runCouncil: (params: Record<string, unknown>, principal: string) => Promise<CouncilRecord>;
  councils: CouncilStore;
  createWorkflow: (params: Record<string, unknown>, credential: AuthenticatedCredential) => Workflow;
  requireWorkflowFor: (workflowId: string, credential: AuthenticatedCredential) => Workflow;
  workflows: WorkflowStore;
  waitWorkflow: (workflowId: string, timeoutMs: number) => Promise<Workflow>;
  cancelWorkflow: (workflowId: string) => Workflow;
  pauseWorkflow: (workflowId: string) => Workflow;
  resumeWorkflow: (workflowId: string) => Workflow;
  validateWorkflow: (params: Record<string, unknown>, credential: AuthenticatedCredential) => unknown;
  createWorkflowDraft: (params: Record<string, unknown>, credential: AuthenticatedCredential) => unknown;
  listWorkflowDrafts: (credential: AuthenticatedCredential) => unknown;
  getWorkflowDraft: (draftId: string, credential: AuthenticatedCredential) => unknown;
  launchWorkflowDraft: (draftId: string, credential: AuthenticatedCredential) => unknown;
  runGate: (params: Record<string, unknown>, principal: string) => unknown;
  enableAutonomy: () => unknown;
  disableAutonomy: () => unknown;
  autonomyStatus: () => unknown;
  createSession: (params: Record<string, unknown>, principal: string) => unknown;
  sendSession: (params: Record<string, unknown>, credential: AuthenticatedCredential) => unknown;
  cancelSession: (sessionId: string, credential: AuthenticatedCredential) => unknown;
  requireSessionFor: (sessionId: string, credential: AuthenticatedCredential) => { result: unknown };
  listSkills: () => unknown;
  inspectSkill: (skill: string) => unknown;
  importSkill: (source: string, actor: string) => unknown;
  enableSkill: (skill: string, actor: string) => unknown;
  useSkill: (params: Record<string, unknown>, credential: AuthenticatedCredential) => unknown;
  revokeSkill: (skill: string) => unknown;
  startLoop: (policy: unknown, credential: AuthenticatedCredential) => unknown;
  listLoops: (credential: AuthenticatedCredential) => unknown;
  statusLoop: (loopId: string, credential: AuthenticatedCredential) => unknown;
  pauseLoop: (loopId: string, credential: AuthenticatedCredential) => unknown;
  resumeLoop: (loopId: string, credential: AuthenticatedCredential) => unknown;
  cancelLoop: (loopId: string, credential: AuthenticatedCredential) => unknown;
  verifyLedger: (evidence: boolean) => unknown;
  repairLedgerTail: (principal: string) => unknown;
  getReceipt: (runId: string) => Receipt | null;
  listReceipts: (opts?: { limit?: number }) => Receipt[];
  verifyReceipt: (runId: string) => ReceiptVerificationVerdict;
  exportReceipt: (runId: string) => ExportedReceipt;
};
