import { resolve } from "node:path";
import { COMMAND_SPECS, STABLE_COMMAND_NAMES } from "../src/cli/command-specs";

export function generatedCommandReference() {
  const rows = COMMAND_SPECS
    .filter((spec) => "help" in spec)
    .map((spec) => {
      const stable = STABLE_COMMAND_NAMES.has(spec.name);
      const aliases = "aliases" in spec ? spec.aliases.join(", ") : "—";
      const usage = stable ? spec.help : `experimental ${spec.help}`;
      return `| \`${spec.name}\` | ${stable ? "Beta 1" : "Experimental"} | ${aliases} | \`${usage}\` |`;
    });
  return [
    "# Command reference",
    "",
    "<!-- Generated by scripts/generate-command-reference.ts. Do not edit by hand. -->",
    "",
    "Default help contains only the Beta 1 execution, project-lifecycle, foreground-lead onboarding, and read-only observer boundary. Every other command requires the explicit `headless experimental` namespace and has no stability promise.",
    "",
    "| Command | Stability | Aliases | Invocation |",
    "| --- | --- | --- | --- |",
    ...rows,
    "",
  ].join("\n");
}

if (import.meta.main) {
  await Bun.write(resolve(import.meta.dir, "../docs/command-reference.md"), generatedCommandReference());
}
